# Generated by Django 3.2.6 on 2021-08-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_countrie', models.CharField(max_length=60, unique=True, verbose_name='Name')),
                ('cities', models.CharField(max_length=60, verbose_name='Cities')),
                ('state', models.CharField(max_length=60, verbose_name='State')),
                ('population', models.IntegerField(verbose_name='Population')),
            ],
        ),
    ]
