# Generated by Django 3.2.6 on 2021-08-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_api', '0002_auto_20210821_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrie',
            name='name_countrie',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
    ]
